[tool.poetry]
name = "gpx-etl"
version = "0.1.0"
description = "Parse, transform, process and create statistics from gpx files."
authors = ["pakdelm <mehrshad.pakdel@posteo.de>"]
license = "Apache License 2.0"

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
pandas = "^1.5.2"
pandas-stubs = "^1.5.2.230105"
numpy = "^1.24.1"
gpxpy = "^1.5.0"
Mypy = "^0.991"
pylint = "^2.15.10"
pytest = "^7.2.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
